name: Course Work CI/CD

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch local server
      run: docker run --name some-nginx -v /home/runner/work/coursework/coursework/html:/usr/share/nginx/html:ro  -p 8080:80 -d nginx
    - name: Try to connect local server
      run: curl http://localhost:8080/
    - name: Run the testing image with web driver Chrome
      run: docker run -p 4444:4444 -p 80:80 -v /dev/shm:/dev/shm -v /home/runner/work/coursework/coursework/tests:/work selenium/standalone-chrome:3.141.59-20200409 python -m unittest -v /work/test.py
      
  deploy:
    runs-on: ubuntu-latest
    needs: [test_main]
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the container
      run: echo ""
