name: Jekyll site CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the container
      run: docker build -t ${{ secrets.DOCKER_USERNAME}}/car_config:nightly ./html
    - name: Deploy ready package
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin;   docker push ${{ secrets.DOCKER_USERNAME }}/car_config:$GITHUB_REF  
  test_main:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
    - uses: actions/checkout@v2
    - name: Launch local server
      run: docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME}}/car_config:$GITHUB_REF
    - name: Try to connect local server
      run: ping http://localhost:80
    - name: Run the testing image with web driver Chrome
      run: docker run -d -p 4444:4444 80:80 -v /dev/shm:/dev/shm $HOME/tests:/work selenium/standalone-chrome:3.141.59-20200409 /work/test.py
      
  deploy:
    runs-on: ubuntu-latest
    needs: [test_main]
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the container
      run: echo "to be implemented"
