name: Jekyll site CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  test_main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch local server
      run: docker run --name some-nginx -v $HOME/html:/usr/share/nginx/html:ro  -p 80:80 -d nginx
    - name: Try to connect local server
      run: docker ps
    - name: Run the testing image with web driver Chrome
      run: docker run -d -p 4444:4444 80:80 -v /dev/shm:/dev/shm $HOME/tests:/work selenium/standalone-chrome:3.141.59-20200409 /work/test.py
      
  deploy:
    runs-on: ubuntu-latest
    needs: [test_main]
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the container
      run: echo "to be implemented"
